import { createContext, useContext, ParentComponent } from "solid-js";
import { useSettings } from "./SettingsContext";

// Translation object
const translations = {
  id: {
    // Sidebar
    dashboard: "Dashboard",
    osp: "OSP",
    security: "Keamanan",
    finance: "Keuangan", 
    settings: "Pengaturan",
    profile: "Profil",
    
    // Dashboard
    systemOverview: "Ringkasan Sistem dan Gambaran Umum",
    cctvFaceRecognition: "CCTV dan Deteksi Wajah",
    paymentsOrFees: "Pembayaran atau Iuran",
    userProfileSystem: "Profil Pengguna dan Preferensi Sistem",
    welcomeBack: "Selamat Datang Kembali",
    systemStatus: "Status Sistem",
    quickActions: "Aksi Cepat",
    recentActivity: "Aktivitas Terbaru",
    systemHealth: "Kesehatan Sistem",
    activeUsers: "Pengguna Aktif",
    totalTransactions: "Total Transaksi",
    
    // OSP
    ospManagement: "Manajemen OSP",
    ospDescription: "Kelola Optical Splitter Panel, task assignment, dan monitoring jaringan fiber optik",
    technicianActivity: "Aktivitas Teknisi",
    activeTechnicians: "Teknisi aktif dan beban kerja",
    taskManagement: "Manajemen Tugas",
    networkMonitoring: "Monitoring Jaringan",
    photoValidation: "Validasi Foto",
    performanceMetrics: "Metrik Performa",
    networkPerformance: "Performa Jaringan",
    realtimeNetworkMonitoring: "Monitoring jaringan real-time",
    uptime: "Waktu Aktif",
    latency: "Latensi",
    bandwidth: "Bandwidth",
    connected: "Terhubung",
    disconnected: "Terputus",
    maintenance: "Maintenance",
    taskOverview: "Ikhtisar Tugas",
    currentTaskStatistics: "Statistik tugas saat ini dan kemajuan",
    activeTasks: "Tugas Aktif:",
    completedTasks: "Tugas Selesai:",
    additionalTasks: "Tugas Tambahan:",
    addNewTask: "Tambah Tugas Baru",
    taskList: "Daftar Tugas",
    manageAndTrackAllTasks: "Kelola dan lacak semua tugas",
    searchTask: "Cari",
    task: "Tugas",
    filterLabel: "Filter:",
    statusFilter: "Status",
    dateFilter: "Tanggal",
    technicianFilter: "Teknisi",
    taskName: "Nama Tugas",
    assignedTo: "Ditugaskan Kepada",
    actionsColumn: "Aksi",
    view: "Lihat",
    photoValidationTitle: "Validasi Foto",
    qualityControlAndValidation: "Kontrol kualitas dan validasi",
    thumbnails: "Thumbnail(s)",
    lowQualityAlert: "Peringatan Kualitas Rendah: Tugas #",
    photoRequiresQualityReview: "Foto memerlukan tinjauan dan validasi kualitas",
    uploadPhoto: "Unggah Foto",
    validate: "Validasi",
    integrationStatus: "Status Integrasi",
    systemIntegrationsConnections: "Integrasi sistem dan koneksi",
    recentActivities: "Aktivitas Terbaru",
    latestOspEventsUpdates: "Peristiwa dan pembaruan OSP terbaru",
    overallProgress: "Kemajuan Keseluruhan",
    statusProgressAllTasks: "Status kemajuan di semua tugas",
    tasksCompleted: "tugas selesai",
    
    // Dashboard additional
    systemPerformance: "Performa Sistem",
    realtimeSystemMonitoring: "Pemantauan sistem real-time",
    cpuUsage: "Penggunaan CPU",
    memoryUsage: "Penggunaan Memori",
    storage: "Penyimpanan",
    operationalSupportPlatform: "Platform Dukungan Operasional",
    activeTasks2: "Tugas Aktif",
    connectedStatus: "Terhubung",
    networkStatus: "Status Jaringan",
    networkUptime: "Uptime Jaringan",
    networkLatency: "Latensi Jaringan",
    bandwidthUsage: "Penggunaan Bandwidth",
    of1Gbps: "dari 1Gbps",
    connectivityBandwidthMonitoring: "Pemantauan konektivitas dan bandwidth",
    recentActivitiesDash: "Aktivitas Terbaru",
    latestSystemEventsUpdates: "Peristiwa dan pembaruan sistem terbaru",
    
    // Status badges
    activeStatus: "Aktif",
    pendingStatus: "Menunggu",
    idleStatus: "Idle",
    completedStatus: "Selesai",
    doneStatus: "Selesai",
    reviewStatus: "Tinjauan",
    inProgressStatus: "Dalam Proses",
    onlineStatus: "Online",
    maintenanceStatus: "Pemeliharaan",
    allFilter: "Semua",
    openAllCameras: "Buka Semua Kamera",
    cameraMonitoring: "Pemantauan Kamera",
    residentsDetected: "Warga Terdeteksi",
    recording: "Merekam",
    liveFeed: "Live Feed",
    active: "Aktif",
    inactive: "Tidak Aktif",
    complete: "Selesai",
    customizeExperience: "Sesuaikan pengalaman Anda",
    today: "Hari Ini",
    totalToday: "Total Hari Ini",
    todaysRecognitions: "Pengenalan Hari Ini",
    // Task Names
    installCCTV: "Pasang CCTV",
    checkFiberOptic: "Cek Fiber Optik",
    repairRouter: "Perbaiki Router",
    networkMaintenance: "Pemeliharaan Jaringan",
    extraWorkPhoto: "Pekerjaan Tambahan (Foto)",
    // Names
    johnDoe: "John Doe",
    mikeTech: "Mike Tech",
    davidP: "David P.",
    unknown: "Tidak Diketahui",
    // Security Page
    systemSecurityStatus: "Status Keamanan Sistem",
    comprehensiveSecurityMonitoring: "Pemantauan sistem keamanan komprehensif dan pengecekan kesehatan",
    encryptionLevel: "Tingkat Enkripsi",
    firewallStatus: "Status Firewall",
    intrusionAttempts: "Percobaan Intrusi",
    dataIntegrity: "Integritas Data",
    lastSecurityScan: "Pemindaian Keamanan Terakhir",
    highPriority: "Prioritas Tinggi",
    resolved: "Selesai",
    recognitionAccuracy: "Akurasi Pengenalan",
    // Profile Page
    editProfile: "Edit Profil",
    lastLogin: "Login Terakhir",
    saveChanges: "Simpan Perubahan",
    // Settings Page
    exportSettings: "Ekspor Pengaturan",
    resetSettings: "Reset Pengaturan",
    verified: "Terverifikasi",
    suspicious: "Mencurigakan",
    
    // Authentication pages
    masuk: "Masuk",
    daftar: "Daftar",
    daftarSekarang: "Daftar Sekarang",
    daftarkanDiri: "Daftarkan diri Anda untuk mendapatkan akses eksklusif ke portal",
    mohonIsiSemua: "Mohon isi semua field yang diperlukan!",
    formatEmailTidakValid: "Format email tidak valid!",
    namaLengkap: "Nama Lengkap",
    masukkanNamaLengkap: "Masukkan nama lengkap",
    masukkanEmail: "Masukkan email",
    password: "Password",
    masukkanPassword: "Masukkan password",
    konfirmasiPassword: "Konfirmasi Password",
    masukkanKonfirmasiPassword: "Masukkan konfirmasi password",
    
    // Security
    securityMonitoring: "Keamanan & Monitoring",
    securityDescription: "Pantau sistem keamanan, CCTV, dan deteksi wajah secara real-time",
    cctvMonitoring: "Monitoring CCTV",
    faceDetection: "Deteksi Wajah",
    accessControl: "Kontrol Akses",
    securityAlerts: "Peringatan Keamanan",
    incidentReports: "Laporan Insiden",
    
    // Finance
    financeManagement: "Manajemen Keuangan",
    financeDescription: "Kelola keuangan dan pembayaran iuran warga dengan mudah",
    totalRevenue: "Total Pendapatan",
    totalExpenses: "Total Pengeluaran",
    netProfit: "Keuntungan Bersih",
    unpaidInvoices: "Tagihan Belum Dibayar",
    totalIuranThisMonth: "Total Iuran Bulan Ini",
    totalResidents: "Total Warga",
    paidResidents: "Warga Sudah Bayar",
    unpaidResidents: "Warga Belum Bayar",
    sudahBayar: "Sudah Bayar",
    outstandingBalance: "Saldo Tertunggak",
    warga: "warga",
    paymentStatusManagement: "Status Pembayaran & Manajemen Warga",
    paymentStatusDescription: "Daftar warga dan status pembayaran iuran bulanan",
    recentTransactions: "Transaksi Terbaru",
    viewAll: "Lihat Semua",
    paymentStatus: "Status Pembayaran",
    paid: "Dibayar",
    pending: "Menunggu",
    unpaid: "Belum Dibayar",
    amount: "Jumlah",
    date: "Tanggal",
    description: "Deskripsi",
    monthlyRevenue: "Pendapatan Bulanan",
    expensesByCategory: "Pengeluaran per Kategori",
    paymentMethods: "Metode Pembayaran",
    creditCard: "Kartu Kredit",
    bankTransfer: "Transfer Bank",
    cash: "Tunai",
    eWallet: "E-Wallet",
    residents: "Warga",
    namaWarga: "Nama Warga", 
    enterResidentName: "Masukkan nama warga",
    
    // Settings
    settingsPreferences: "Pengaturan & Preferensi",
    settingsDescription: "Kelola pengaturan akun, preferensi sistem, dan konfigurasi aplikasi",
    preferences: "Preferensi",
    language: "Bahasa",
    theme: "Tema",
    notifications: "Notifikasi",
    securitySettings: "Keamanan",
    changePassword: "Ubah Kata Sandi",
    currentPassword: "Kata Sandi Saat Ini",
    newPassword: "Kata Sandi Baru",
    confirmPassword: "Konfirmasi Kata Sandi Baru",
    updatePassword: "Perbarui Kata Sandi",
    activeSessions: "Sesi Aktif",
    systemSettings: "Pengaturan Sistem",
    userManagement: "Manajemen Pengguna",
    name: "Nama",
    email: "Email", 
    role: "Peran",
    status: "Status",
    actions: "Tindakan",
    databaseBackup: "Backup Database",
    systemMaintenance: "Pemeliharaan Sistem",
    recentSystemLogs: "Log Sistem Terbaru",
    endSession: "Akhiri Sesi",
    current: "Saat Ini",
    lastActive: "Terakhir Aktif",
    adminOnly: "Khusus Admin",
    adminOnlyDescription: "Manajemen sistem khusus admin",    // Profile
    userProfile: "Profil Pengguna",
    profileDescription: "Kelola informasi pribadi, aktivitas, dan keamanan akun Anda",
    
    // Theme
    lightMode: "Mode Terang",
    darkMode: "Mode Gelap",
    switchToDark: "Beralih ke Mode Gelap",
    switchToLight: "Beralih ke Mode Terang",
    
    // Language
    bahasa: "Bahasa Indonesia",
    english: "English",
    switchToEnglish: "Beralih ke English",
    switchToIndonesian: "Beralih ke Bahasa Indonesia",
    
    // Common
    save: "Simpan",
    cancel: "Batal",
    edit: "Edit",
    delete: "Hapus",
    add: "Tambah",
    search: "Cari",
    filter: "Filter",
    export: "Ekspor",
    import: "Impor",
    loading: "Memuat...",
    error: "Kesalahan",
    success: "Berhasil",
    warning: "Peringatan",
    info: "Informasi",
    
    // Additional missing translations
    logoutAllOthers: "Logout Semua Lainnya",
    overallSystemUptime: "Uptime Sistem Keseluruhan",
    openAllCameraFeeds: "Buka Semua Feed Kamera",
    all: "Semua",
    notConnected: "Tidak terhubung",
    
    // Authentication
    emailField: "Email",
    passwordField: "Kata Sandi",
    rememberMe: "Ingat Saya",
    signIn: "Masuk",
    signUp: "Daftar",
    forgotPassword: "Lupa Kata Sandi",
    pleaseEnterAllFields: "Mohon isi semua field yang diperlukan!",
    invalidEmailFormat: "Format email tidak valid!",
    contactMarketing: "Hubungi Marketing",
    housesBuilt: "Rumah Dibangun",
    yearsExperience: "Tahun Pengalaman",
    projectsCompleted: "Proyek Selesai",
    trustedDeveloper: "Developer Terpercaya",
    qualityAssured: "Kualitas Terjamin",
    activeDetections: "Deteksi Aktif",
    activeEmployees: "Karyawan Aktif",
    resetAllSettingsConfirm: "Apakah Anda yakin ingin mereset semua pengaturan ke default? Tindakan ini tidak dapat dibatalkan.",
    firewallActive: "Aktif",
    resetConfirmation: "Apakah Anda yakin ingin reset semua pengaturan ke default? Tindakan ini tidak dapat dibatalkan."
  },
  en: {
    // Sidebar
    dashboard: "Dashboard",
    osp: "OSP",
    security: "Security",
    finance: "Finance",
    settings: "Settings", 
    profile: "Profile",
    
    // Dashboard
    systemOverview: "System Overview and Summary",
    cctvFaceRecognition: "CCTV and Face Recognition",
    paymentsOrFees: "Payments or Fees",
    userProfileSystem: "User Profile and System Preferences",
    welcomeBack: "Welcome Back",
    systemStatus: "System Status",
    quickActions: "Quick Actions",
    recentActivity: "Recent Activity",
    systemHealth: "System Health",
    activeUsers: "Active Users",
    totalTransactions: "Total Transactions",
    
    // OSP
    ospManagement: "OSP Management",
    ospDescription: "Manage Optical Splitter Panel, task assignment, and fiber optic network monitoring",
    technicianActivity: "Technician Activity",
    activeTechnicians: "Active technicians and workload",
    taskManagement: "Task Management",
    networkMonitoring: "Network Monitoring",
    photoValidation: "Photo Validation",
    performanceMetrics: "Performance Metrics",
    networkPerformance: "Network Performance",
    realtimeNetworkMonitoring: "Real-time network monitoring",
    uptime: "Uptime",
    latency: "Latency",
    bandwidth: "Bandwidth",
    connected: "Connected",
    disconnected: "Disconnected",
    maintenance: "Maintenance",
    taskOverview: "Task Overview",
    currentTaskStatistics: "Current task statistics and progress",
    activeTasks: "Active Tasks:",
    completedTasks: "Completed Tasks:",
    additionalTasks: "Additional Tasks:",
    addNewTask: "Add New Task",
    taskList: "Task List",
    manageAndTrackAllTasks: "Manage and track all tasks",
    searchTask: "Search",
    task: "Task",
    filterLabel: "Filter:",
    statusFilter: "Status",
    dateFilter: "Date",
    technicianFilter: "Technician",
    taskName: "Task Name",
    assignedTo: "Assigned To",
    actionsColumn: "Actions",
    view: "View",
    photoValidationTitle: "Photo Validation",
    qualityControlAndValidation: "Quality control and validation",
    thumbnails: "Thumbnail(s)",
    lowQualityAlert: "Low Quality Alert: Task #",
    photoRequiresQualityReview: "Photo requires quality review and validation",
    uploadPhoto: "Upload Photo",
    validate: "Validate",
    integrationStatus: "Integration Status",
    systemIntegrationsConnections: "System integrations and connections",
    recentActivities: "Recent Activities",
    latestOspEventsUpdates: "Latest OSP events and updates",
    overallProgress: "Overall Progress",
    statusProgressAllTasks: "Status progress across all tasks",
    tasksCompleted: "tasks completed",
    
    // Dashboard additional
    systemPerformance: "System Performance",
    realtimeSystemMonitoring: "Real-time system monitoring",
    cpuUsage: "CPU Usage",
    memoryUsage: "Memory Usage",
    storage: "Storage",
    operationalSupportPlatform: "Operational Support Platform",
    activeTasks2: "Active Tasks",
    connectedStatus: "Connected",
    networkStatus: "Network Status",
    networkUptime: "Network Uptime",
    networkLatency: "Network Latency", 
    bandwidthUsage: "Bandwidth Usage",
    of1Gbps: "of 1Gbps",
    connectivityBandwidthMonitoring: "Connectivity and bandwidth monitoring",
    recentActivitiesDash: "Recent Activities",
    latestSystemEventsUpdates: "Latest system events and updates",
    
    // Status badges
    activeStatus: "Active",
    pendingStatus: "Pending",
    idleStatus: "Idle",
    completedStatus: "Completed",
    doneStatus: "Done",
    reviewStatus: "Review",
    inProgressStatus: "In Progress",
    onlineStatus: "Online",
    maintenanceStatus: "Maintenance",
    allFilter: "All",
    openAllCameras: "Open All Cameras",
    cameraMonitoring: "Camera Monitoring",
    residentsDetected: "Residents Detected",
    recording: "Recording",
    liveFeed: "Live Feed",
    active: "Active",
    inactive: "Inactive",
    complete: "Complete",
    customizeExperience: "Customize your experience",
    today: "Today",
    totalToday: "Total Today",
    todaysRecognitions: "Today's Recognitions",
    // Task Names
    installCCTV: "Install CCTV",
    checkFiberOptic: "Check Fiber Optic",
    repairRouter: "Repair Router", 
    networkMaintenance: "Network Maintenance",
    extraWorkPhoto: "Extra Work (Photo)",
    // Names
    johnDoe: "John Doe",
    mikeTech: "Mike Tech",
    davidP: "David P.",
    unknown: "Unknown",
    // Security Page
    systemSecurityStatus: "System Security Status",
    comprehensiveSecurityMonitoring: "Comprehensive security system monitoring and health check",
    encryptionLevel: "Encryption Level",
    firewallStatus: "Firewall Status",
    intrusionAttempts: "Intrusion Attempts",
    dataIntegrity: "Data Integrity",
    lastSecurityScan: "Last Security Scan",
    highPriority: "High Priority", 
    resolved: "Resolved",
    recognitionAccuracy: "Recognition Accuracy",
    // Profile Page  
    editProfile: "Edit Profile",
    lastLogin: "Last Login",
    saveChanges: "Save Changes",
    // Settings Page
    exportSettings: "Export Settings",
    resetSettings: "Reset Settings",
    verified: "Verified",
    suspicious: "Suspicious",
    
    // Authentication pages
    masuk: "Sign In",
    daftar: "Sign Up",
    daftarSekarang: "Sign Up Now",
    daftarkanDiri: "Register yourself to get exclusive access to the portal",
    mohonIsiSemua: "Please fill in all required fields!",
    formatEmailTidakValid: "Invalid email format!",
    namaLengkap: "Full Name",
    masukkanNamaLengkap: "Enter full name",
    masukkanEmail: "Enter email",
    password: "Password",
    masukkanPassword: "Enter password",
    konfirmasiPassword: "Confirm Password",
    masukkanKonfirmasiPassword: "Enter password confirmation",
    
    // Security
    securityMonitoring: "Security & Monitoring",
    securityDescription: "Monitor security systems, CCTV, and real-time face detection",
    cctvMonitoring: "CCTV Monitoring",
    faceDetection: "Face Detection",
    accessControl: "Access Control",
    securityAlerts: "Security Alerts",
    incidentReports: "Incident Reports",
    
    // Finance
    financeManagement: "Finance Management",
    financeDescription: "Manage finances and resident fee payments easily",
    totalRevenue: "Total Revenue",
    totalExpenses: "Total Expenses", 
    netProfit: "Net Profit",
    unpaidInvoices: "Unpaid Invoices",
    totalIuranThisMonth: "Total Contribution This Month",
    totalResidents: "Total Residents",
    paidResidents: "Paid Residents",
    unpaidResidents: "Unpaid Residents",
    sudahBayar: "Paid",
    outstandingBalance: "Outstanding Balance",
    warga: "residents",
    paymentStatusManagement: "Payment Status & Resident Management",
    paymentStatusDescription: "List of residents and monthly fee payment status",
    recentTransactions: "Recent Transactions",
    viewAll: "View All",
    paymentStatus: "Payment Status",
    paid: "Paid",
    pending: "Pending",
    unpaid: "Unpaid",
    amount: "Amount",
    date: "Date",
    description: "Description",
    monthlyRevenue: "Monthly Revenue",
    expensesByCategory: "Expenses by Category",
    paymentMethods: "Payment Methods",
    creditCard: "Credit Card",
    bankTransfer: "Bank Transfer",
    cash: "Cash",
    eWallet: "E-Wallet",
    residents: "Residents",
    namaWarga: "Resident Name",
    enterResidentName: "Enter resident name",
    
    // Settings
    settingsPreferences: "Settings & Preferences", 
    settingsDescription: "Manage account settings, system preferences, and application configuration",
    preferences: "Preferences",
    language: "Language",
    theme: "Theme",
    notifications: "Notifications",
    securitySettings: "Security",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    updatePassword: "Update Password",
    activeSessions: "Active Sessions",
    systemSettings: "System Settings",
    userManagement: "User Management",
    name: "Name",
    email: "Email", 
    role: "Role",
    status: "Status",
    actions: "Actions",
    databaseBackup: "Database Backup",
    systemMaintenance: "System Maintenance",
    recentSystemLogs: "Recent System Logs",
    endSession: "End Session",
    current: "Current",
    lastActive: "Last Active",
    adminOnly: "Admin Only",
    adminOnlyDescription: "Admin-only system management",
    
    // Profile
    userProfile: "User Profile",
    profileDescription: "Manage personal information, activities, and account security",
    
    // Theme
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    switchToDark: "Switch to Dark Mode",
    switchToLight: "Switch to Light Mode",
    
    // Language
    bahasa: "Bahasa Indonesia",
    english: "English",
    switchToEnglish: "Switch to English",
    switchToIndonesian: "Switch to Bahasa Indonesia",
    
    // Common
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Information",
    
    // Additional missing translations
    logoutAllOthers: "Logout All Others",
    overallSystemUptime: "Overall System Uptime",
    openAllCameraFeeds: "Open All Camera Feeds",
    all: "All",
    notConnected: "Not connected",
    
    // Authentication
    emailField: "Email",
    passwordField: "Password",
    rememberMe: "Remember Me",
    signIn: "Sign In",
    signUp: "Sign Up",
    forgotPassword: "Forgot Password",
    pleaseEnterAllFields: "Please fill in all required fields!",
    invalidEmailFormat: "Invalid email format!",
    contactMarketing: "Contact Marketing",
    housesBuilt: "Houses Built",
    yearsExperience: "Years Experience",
    projectsCompleted: "Projects Completed",
    trustedDeveloper: "Trusted Developer",
    qualityAssured: "Quality Assured",
    activeDetections: "Active Detections",
    activeEmployees: "Active Employees",
    resetAllSettingsConfirm: "Are you sure you want to reset all settings to default? This action cannot be undone.",
    firewallActive: "Active",
    resetConfirmation: "Are you sure you want to reset all settings to default? This action cannot be undone."
  }
};

export interface LanguageContextType {
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>();

export const LanguageProvider: ParentComponent = (props) => {
  const { settings } = useSettings();
  
  const t = (key: string): string => {
    const currentLang = settings().language;
    const translation = translations[currentLang]?.[key];
    return translation || key;
  };

  const contextValue: LanguageContextType = {
    t
  };

  return (
    <LanguageContext.Provider value={contextValue}>
      {props.children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
